variables:
  DEPLOY_USER: sh3292
  DEPLOY_URL: tux.cs.drexel.edu
  DEPLOY_PATH: ~/public_html/
  S3_BUCKET_NAME: saffat-resume-bucket

stages:
  - check
  - generate-source
  - build
  - deploy

check-python:
  image: python:3.8
  stage: check
  script:
    - pip install -r src/requirements.txt
    - pylint src/

check-terraform:
  # https://matavelli.io/posts/2020/01/setup-gitlab-ci-with-terraform/
  stage: check
  image:
    name: hashicorp/terraform
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  before_script:
    - cd terraform/
    - terraform init
  script:
    - terraform validate
  cache:
    key: terraform
    paths:
      - terraform/.terraform

generate-sources:
  stage: generate-source
  image: python:3.8
  script:
    - pip install -r src/requirements.txt
    - python src/main.py resume
    - python src/main.py resume-simple
  artifacts:
    paths:
      - dist/

generate-resumes:
  stage: build
  image: blang/latex:ubuntu
  script:
    - cp resources/mcdowellcv.cls dist
    - cd dist
    - lualatex resume.tex
    - lualatex resume-simple.tex
  artifacts:
    paths:
      - dist/resume.pdf
      - dist/resume-simple.pdf
  dependencies:
    - generate-sources

deploy-to-tux:
  stage: deploy
  only:
    refs:
      - master
  script:
    - apt-get update -qq && apt-get install -y -qq sshpass
    - sshpass -e scp -o stricthostkeychecking=no dist/*.pdf $DEPLOY_USER@$DEPLOY_URL:$DEPLOY_PATH

create-bucket:
  # https://matavelli.io/posts/2020/01/setup-gitlab-ci-with-terraform/
  stage: deploy
  only:
    refs:
      - master
  image:
    name: hashicorp/terraform
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  before_script:
    - cd terraform/
    - terraform init
  script:
    - terraform validate
    - terraform plan --out plan
    - terraform apply --auto-approve plan
  cache:
    key: terraform
    paths:
      - terraform/.terraform

deploy-to-s3:
  stage: deploy
  only:
    refs:
      - master
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp ./dist s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.pdf"
  dependencies:
    - create-bucket
