stages:
  - generate-source
  - build

generate-sources:
  stage: generate-source
  image: python:3.8
  script:
    - pip install -r src/requirements.txt
    - python src/main.py
  artifacts:
    paths:
      - dist/

generate-resumes:
  stage: build
  image: blang/latex:ubuntu
  script:
    - cp archive/mcdowellcv.cls dist
    - cd dist
    - lualatex resume.tex
    - lualatex resume-simple.tex
    - ls
    - find .
  artifacts:
    paths:
      - resume.pdf
      - resume-simple.pdf
      - dist/resume.pdf
      - dist/resume-simple.pdf
      - dist/
  dependencies:
    - generate-sources
