stages:
  - generate-source
  - build

generate-pdf:
  stage: build
  image: blang/latex:ubuntu
  script:
    - cd archive
    - lualatex main.tex
  artifacts:
    paths:
      - archive/main.pdf

generate-source:
  stage: generate-source
  image: python:3.8
  script:
    - pip install src/requirements.txt
    - python src/main.py
  artifacts:
    paths:
      - dist/

generate-pdf-2:
  stage: build
  image: blang/latex:ubuntu
  script:
    - cp archive/mcdowellcv.cls dist
    - cd dist
    - lualatex output.tex
  artifacts:
    paths:
      - archive/output.pdf
  dependencies:
    - generate-source
