name: Style

on: [push]

jobs:
  lint-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint src/

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ibiqlik/action-yamllint@v3.1.0
